config/routes.rb
Rails.application.routes.draw do

  get '/my_wikis', to: 'wikis#my_wikis'
    
  resources :upgrade

  resources :wikis do
    resources :collaborators, only: [:index, :create, :destroy]
  end

  devise_for :users

  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :set_defaults
  after_update :complete_downgrade

  has_many :wikis, :dependent => :delete_all
  has_many :collaborators, :dependent => :delete_all

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  enum role: [:member, :premium, :admin]

  private
  def set_defaults
    self.role ||= :member
  end

  def complete_downgrade
    if self.role_changed? && self.role != 'premium' then
        wikis = Wiki.where(user_id: self.id)
        wikis.each do |w|
            w.private = false
            w.save!
        end
    end
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators, :dependent => :delete_all
  #TODO: this needs to be able to access current_user to work
  #scope :owned_by, -> { where(user_id: 1)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def require_login
    unless current_user
      flash[:alert] = "You must be logged in to do that"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
    before_action :require_login
    before_action :set_wiki
    
    def index
      logger.info "INDEX"
      logger.info params
      @wiki_id = params[:wiki_id]
      @collaborators = User.joins('left join collaborators on users.id = collaborators.user_id where collaborators.wiki_id is null or collaborators.wiki_id = ' + params[:wiki_id]).select('users.email, collaborators.id, users.id as user_id, collaborators.wiki_id').order(:email)
    end

    def create
      logger.info "CREATE"
      logger.info params

      c = @wiki.collaborators.new(user_id: params[:user][:user_id])
      
      if c.save! then
        flash[:notice] = "Collaborator added successfully!"
      else
        flash[:alert] = "Unable to add collaborator :("
      end

      redirect_to wiki_collaborators_path(@wiki)
    end

    def destroy
      logger.info "DESTROY"
      logger.info params

      collab = Collaborator.find(params[:user][:collab_id])

      if collab.destroy! then
        flash[:notice] = "Collaborator removed successfully!"
      else 
        flash[:notice] = "Unable to remove collaborator :("
      end

      redirect_to wiki_collaborators_path(@wiki)
    end 

    private

    def set_wiki
      @wiki = Wiki.find(params[:wiki_id])
    end
end

app/controllers/upgrade_controller.rb
class UpgradeController < ApplicationController
  before_action :require_login

  def show
    @user = User.find(params[:id])
    @stripe_btn_data = {
        key: "#{ Rails.configuration.stripe[:publishable_key] }",
        description: "Bloccit Membership - #{current_user.email}",
        amount: 1000
    }
  end

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: 1000,
     description: "Bloccit Membership - #{current_user.email}",
     currency: 'usd'
    )

    current_user.role = 'premium'
    current_user.save!

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    redirect_to edit_user_registration_path(current_user)

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
     flash[:alert] = e.message
     puts "error"
     puts e.message
     redirect_to upgrade_path(current_user.id)
    end

    def destroy
      current_user.role = 'member'
      current_user.save!

      redirect_to edit_user_registration_path
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    @wikis = Wiki.where(private: false)
  end

  def my_wikis
    @wikis = Wiki.where(user_id: current_user.id)
    if @wikis == nil then
      @wikis = []
    end
  end

  def show
    @wiki = Wiki.joins(:user).find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user_id = current_user.id

    if @wiki.save!
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error, please try again"
      render :new
    end
  end

  def edit
    @wiki = Wiki.joins(:user).find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    if @wiki.save!
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error, please try again"
      render :new
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    if @wiki.destroy then
      flash[:notice] = "Wiki was deleted sucessfully."
    else
      flash[:alert] = "Error deleting wiki."
    end
    redirect_to :my_wikis
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def can_upgrade
        return current_user && current_user.role != 'premium'
    end

    def to_markdown(t)
        # renderer = Redcarpet::Render::HTML.new
        # rc = Redcarpet::Markdown.new(renderer)
        rc = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
        rc.render(t).html_safe
    end
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/upgrade_helper.rb
module UpgradeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def can_edit(wiki)
    collaborator_ids = [] 
    # wiki_collaborators = Wiki.select('collaborators.user_id').where(id: wiki.id).joins(:collaborators)
    wiki.collaborators.each do |wc|
       collaborator_ids.push(wc.user_id) 
    end

    logger.info "collab ids"
    logger.info collaborator_ids

    return (current_user.id == wiki.user_id || current_user.role == 'admin' || collaborator_ids.include?(current_user.id))
  end

  def can_delete(wiki)
    return current_user && current_user.role = 'admin'
  end
end

app/views/collaborators/index.html.erb
<ul class="list-group center-list">
    <% @collaborators.each do |c| %>
        <li class="list-group-item">
            <%= c.email %>
            <%= c.user_id %>
            <%= c.id %>
            <%= form_for c, url: c.wiki_id == nil ? wiki_collaborators_path(@wiki_id) : wiki_collaborator_path(@wiki_id, c.id), method: c.wiki_id == nil ? :post : :delete do |f| %>
                <%= f.hidden_field :wiki_id, value: @wiki_id %>
                <%= f.hidden_field :user_id, value: c.user_id %>
                <%= f.hidden_field :collab_id, value: c.id %>
                <% if c.id == nil %>
                    <%= f.submit "Add", class: "btn btn-primary", type: "submit" %>
                <% else %>
                    <%= f.submit "Remove", class: "btn btn-primary", type: "submit" %>
                <% end %>
            <% end %>
        </li>
    <% end %>
</ul>

app/views/collaborators/show.html.erb
<ul class="list-group center-list">
    <% @collaborators.each do |c| %>
        <li class="list-group-item">
            <%= c.email %>
            <%= c.user_id %>
            <%= c.id %>
            <%= form_for c, url: c.wiki_id == nil ? collaborators_path : collaborator_path, method: c.wiki_id == nil ? :post : :delete do |f| %>
                <%= f.hidden_field :wiki_id, value: @wiki_id %>
                <%= f.hidden_field :user_id, value: c.user_id %>
                <%= f.hidden_field :collab_id, value: c.id %>
                <% if c.id == nil %>
                    <%= f.submit "Add", class: "btn btn-primary", type: "submit" %>
                <% else %>
                    <%= f.submit "Remove", class: "btn btn-primary", type: "submit" %>
                <% end %>
            <% end %>
        </li>
    <% end %>
</ul>

<%#= link_to "Add", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: "btn" %>

<!-- params[:user_id]

def collaborator_for(user)
    collbaorators.where(user_id: user.id).first
end -->

<%#= @wiki.collaborator_for(user) %>
<%#= link_to "Remove", [@wiki, collaborator], method: :delete, class: "btn  btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Blocipedia</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css" crossorigin="anonymous">
    <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js" crossorigin="anonymous"></script> -->   
    <%= csrf_meta_tags %>
</head>
<body>
    <div id="main">
        <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
            <div class="nav navbar-nav">
                <%= link_to "Home", root_path,  class: "nav-item nav-link" %>
                <a class="nav-item nav-link" href="/wikis">Wikis</a>
                <a class="nav-item nav-link" href="#">Placeholder</a>
            </div>
            <div class="nav navbar-nav pull-xs-right">
                <% if user_signed_in? %>
                    Signed in as: <strong><%= current_user.email %></strong>
                    <%= link_to 'My Wikis', my_wikis_path, :class => 'nav-item nav-link' %>
                    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-item nav-link' %>
                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'nav-item nav-link'  %>
                <% else %>
                    <%= link_to "Sign Up", new_user_registration_path, :class => 'nav-item nav-link'  %>
                    <%= link_to "Sign In", new_user_session_path, :class => 'nav-item nav-link'  %>
                <% end %>
            </div>
        </nav>
        <br/>
        <div class="flash">
            <% if flash[:notice] %>
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <%= flash[:notice] %>
                </div>
            <% elsif flash.now[:alert] %>
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <%= flash.now[:alert] %>
                </div>
            <% elsif flash[:alert] %>
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <%= flash[:alert] %>
                </div>
            <% end %>
        </div>
<%= yield %>
</body>
</html>

app/views/upgrade/index.html.erb
<h1>Upgrade#index</h1>
<p>Find me in app/views/upgrade/index.html.erb</p>
<%= form_tag upgrade_upgrade_path do %> 
    <h4>Click the button!</h4>
        <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/upgrade/show.html.erb
<%= form_tag upgrade_index_path do %> 
    <h4>Click the button!</h4>
        <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/upgrade/upgrade.html.erb
<h1>Upgrade#upgrade</h1>
<p>Find me in app/views/upgrade/upgrade.html.erb</p>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-3">Blocipedia</h1>
    <p class="lead">Social, Markdown Wikis</p>
    <hr class="m-y-2">
    <p>Create and share Markdown Wikis. Get started today!</p>
    <p class="lead">
      <%= link_to "Sign Up", new_user_registration_path,  class: "btn btn-primary btn-lg" %>
    </p>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="card card-block">
        <h3 class="card-title">Free Plan</h3>
        <p class="card-text">Here's what you can do with a free plan.</p>
        <a href="#" class="btn btn-primary">Learn More</a>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card card-block">
        <h3 class="card-title">Premium Plan</h3>
        <p class="card-text">Here's why a premium plan is better.</p>
        <a href="#" class="btn btn-primary">Learn More</a>
      </div>
    </div>
  </div>
</div>

app/views/wikis/edit.html.erb
<div id="wiki-form-container">
  <%= form_for @wiki do |f| %>

    <fieldset class="form-group">
      <div class="field">
        <label for="title">Title</label>
        <%= f.text_field :title, id: "title", class: "form-control", placeholder: "Wiki Title" %>
      </div>
    </fieldset>

    <fieldset class="form-group">
      <div class="field">
        <label for="body">Body</label>
        <%= f.text_area :body, id: "body", class: "form-control", placeholder: "Wiki Body" %>
      </div>
    </fieldset>

    <% if current_user.role = 'premium' || current_user.role == 'admin' %>
      <fieldset class="form-group">
        <div class="field">
          <label for="private">Private?</label>
          <%= f.check_box :private, id: "private", class: "form-control" %>
        </div>
      </fieldset>
    <% end %>

    <%= f.submit "Update", class: "btn btn-primary", type: "submit" %>
  <% end %>
</div>

app/views/wikis/index.html.erb
<% if current_user %>
    <%= button_to "New Wiki", new_wiki_path, method: :get, class: "btn btn-primary" %>
<% end %>
<ul class="list-group wiki-list">
    <% @wikis.each do |wiki| %>
        <li class="list-group-item"><%= link_to wiki.title, wiki %>
            <% if can_edit(wiki) %>
                <%= link_to "Edit", edit_wiki_path(wiki) %>
            <% end %>
            <% if can_delete(wiki) %>
                <%= link_to "Delete", wiki_path(wiki), method: :delete, data: { confirm: 'Are you sure you want to delete this wiki?' } %>
            <% end %>
        </li>
    <% end %>
</ul>

app/views/wikis/my_wikis.html.erb
<ul class="list-group wiki-list">
    <% @wikis.each do |wiki| %>
        <li class="list-group-item">
            <%= link_to wiki.title, wiki %>
            <%= link_to "Edit", edit_wiki_path(wiki) %>
            <%= link_to "Delete", wiki_path(wiki), method: :delete, data: { confirm: 'Are you sure you want to delete this wiki?' } %>
        </li>
    <% end %>
</ul>

app/views/wikis/new.html.erb
<div id="wiki-form-container">
  <%= form_for @wiki do |f| %>

    <fieldset class="form-group">
      <div class="field">
        <label for="title">Title</label>
        <%= f.text_field :title, id: "title", class: "form-control", placeholder: "Wiki Title" %>
      </div>
    </fieldset>

    <fieldset class="form-group">
      <div class="field">
        <label for="body">Body</label>
        <%= f.text_area :body, id: "body", class: "form-control", placeholder: "Wiki Body" %>
      </div>
    </fieldset>

    <% if current_user.role = 'premium' || current_user.role == 'admin' %>
      <fieldset class="form-group">
        <div class="field">
          <label for="private">Private?</label>
          <%= f.check_box :private, id: "private", class: "form-control" %>
        </div>
      </fieldset>
    <% end %>

    <%= f.submit "Create", class: "btn btn-primary", type: "submit" %>
  <% end %>
</div>

app/views/wikis/show.html.erb
<div id="wiki-container">
    <% if @wiki.user_id == current_user.id %>
        <%= button_to "Add Collaborator", wiki_collaborators_path(@wiki.id), method: :get, class: "btn btn-primary" %>
    <% end %>
    <% if can_edit(@wiki) %>
      <%= button_to "Edit", edit_wiki_path(@wiki.id), method: :get, class: "btn btn-primary" %>
    <% end %>
    <h2><u><%= @wiki.title %></u></h2>
    <p><small>Created by <%= @wiki.user.email %> at <%= @wiki.created_at %> and last updated <%= @wiki.updated_at %></small></p>
    <p><%= to_markdown(@wiki.body) %></p>
</div>